### ISSUE TITLE
First class support for device sizes to breakpoints mapping in blade

### ISSUE THREAD

**Issue by anilprzp** [razorpay/blade#1133]
## Problem statement
Writing media-queries can feel very repetitive overtime. In a structured design system like blade, a media query would always correspond to either mobile, tablet or desktop device(the list of devices can be larger also) and we have to write the same media query for numerous times, i.e `@media screen and (min-width: ${theme.breakpoints.s}px)`, this gets very repetitive and involves remembering the breakpoints that corresponds to a device. Also no-one really remembers what breakpoints  belongs to what devices, I personally have to keep revisiting the blade docs for checking this and then writing media queries.

## Solution
In x-acquisition we have been using a utility for writing media queries which provides an API that bridges the gap between device and its corresponding media-query and it has been helping us a ton in writing faster media queries. Here is an example of what I'm talking about - 
So this is regular usage of media-queries with blade - 
```javascript
const Component = styled.div(({ theme }) => `
  @media (max-width: ${theme.breakpoints.s}px) {
    // some styles for mobile device
  }

  @media (min-width: ${theme.breakpoints.s}px and max-width: ${theme.breakpoints.l}) {
    // some styles for tablet device
  }

  @media (min-width: ${theme.breakpoints.l}px) {
    // some styles for desktop device
  }
`);
```

and this is how the utility replaces it - 
```javascript
const Component = styled.div(({ theme }) => `
  ${mediaQueryUtility.mobile`
    // some styles for mobile device
  `}

  ${mediaQueryUtility.tablet`
    // some styles for tablet device
  `}

  ${mediaQueryUtility.desktop`
    // some styles for desktop device
  `}
`);
```
Note - The code snippets are only for representing the idea, please ignore any minor intricacies.

## Proposal
Blade design system can have a similar utility with an API that directly maps devices to media queries as described above. Benefits of having such utility - 
- Uniformity across the whole application for device specific code
- Developer productivity is improved

## Resources
The implementation and usage of same in x-acquisition can be found here - 
Implementation - https://github.com/razorpay/x/blob/master/src/js/views/MasterOnboarding/OneCaOnboarding/helpers.ts#L118
Usage - https://github.com/razorpay/x/blob/master/src/js/views/MasterOnboarding/OneCaOnboarding/RblDeclarations/styles.ts#L10

**Comment by anilprzp** [comment]
I'm creating this issue to have an initial discussion on this and how to proceed further. I'll be happy to take this forward.

**Comment by cseas** [comment]
The linked example usage doesn't look intuitive to me.
> [Hell is other people’s abstractions][1]

```js
${styledComponentsScreenMediaQueries.tabletAndDesktop`
    // styles
`}
```

The intention of the proposal is to avoid the mental overhead of having to go through documentation/implementation to understand what the util really does. The above usage doesn't indicate whether the query being added is for max-width or min-width so that can cause confusion.

We solved this in a previous org by providing media queries for both max and min widths.

Example:

```js
${mediaQuery.minWidth.tablet`
    // styles
`}

${mediaQuery.maxWidth.mobile`
    // styles
`}
```

^ This API would be more intuitive to understand without having to check docs.

However, this does push forward our dependence on CSS-in-JS as the above syntax will mostly work only with some runtime styling library. Example, for Vanilla Extract, you'll need to omit the `@media` for the util to be useful for consumers. So Blade pushing the usage of styled-components further sounds counter-productive as we're discussing moving towards [static styles][2].

I do agree if Blade had semantic tokens, that would've helped a lot.
`theme.breakpoints.s` means nothing to me as a developer without reading Blade docs.

Having semantic tokens like `theme.breakpoints.mobile` would help make the usage code a lot more readable. Plus, tokens will always work for all consumers regardless of what styling solution they choose to use.

Writing the `@media (min-width:` part gets a bit repetitive, agree. But for a short term discomfort, we get readable code for long term maintainability.

[1]: https://twitter.com/dan_abramov/status/1368710730812432389
[2]: https://github.com/razorpay/blade/issues/432

**Comment by anilprzp** [comment]
The core problem that I'm trying to address is the unavailability of a first-class mapping of device sizes with blade's existing breakpoint tokens. 

As @cseas pointed out that having device specific breakpoint tokens would make code much more readable. Blade consumers generally don't have an idea of which breakpoints are mapped to which devices. We have [this documentation](https://master--61c19ee8d3d282003ac1d81c.chromatic.com/?path=/docs/tokens-breakpoints--page&globals=measureEnabled:false#-breakpoints) for it but again its not a first-class way but a second-class way.

**Comment by saurabhdaware** [comment]
Thanks for creating the issue @anilprzp !! Love having these discussions 🥳 

Opinions:
- So I think from blade's end we might push for having responsive styles as props as we have added in Box and also styled-props of other components now - https://blade.razorpay.com/?path=/docs/components-layout-primitives-box-layout-primitives-tutorial--page#responsive-props. So overall I expect usage of media queries to come down as this is used more. ( I agree that there will still be places where you might have to write media queries for custom components)
- There is a "abstraction vs learning curve" tradeoff that we might have to consider here. I wouldn't exactly count writing media queries again as repetitive code and in some cases if you feel like you're repeating it, having local abstractions should be fine. Introducing new utility would introduce new thing for people to learn and adopt. 
- Also btw In the example you gave, I don't think so you would need to have `maxWidth` queries anywhere right? just using `min-width` query should cover all scenarios no? These are the media queries we follow in responsive props now -
https://github.com/razorpay/blade/blob/74c063930c12ddd92f47fc93b2f382dd67382607/packages/blade/src/tokens/global/breakpoints.ts#L29-L68
- There are some gotchas with media queries depending on how they are used.
  - E.g. if you're using them as media query in CSS, you can just define `min-width` and the next `min-width` query overrides previous so the media queries in above point works perfectly in CSS since `min-width: large` would override styles of `min-width: small`. 
  - But when you use the same media queries in JavaScript (in `window.matchMedia`), you also have to define max-width query otherwise `min-width: small` becomes true on all devices starting small.
- We earlier had a small discussion of calling our breakpoint tokens with `breakpoints.mobile`, `breakpoints.,desktop` rather than `breakpoints.s`, `breakpoints.m` but we wanted to avoid any confusion between smallMobile, largeTablets kind of naming (Check out note in [ref](https://github.com/razorpay/blade/blob/master/rfcs/2023-01-06-layout.md#responsive-styles)). 
  - This would also stop us from adding more breakpoints in future, Can't name a breakpoint `largerThanSmallMobileSmallerThanLargeMobile` if we were to add a new breakpoint. 😆 
  - Also tokens depend on whether you use `min-width` or `max-width`. E.g. `min-width: breakpoint.m` is tablet and `max-width: breakpoint.m` is mobile. So we can't replace `breakpoint.m` with `breakpoint.tablet` since that can be misleading.


We can wait for opinions from other team members as well. Thanks for starting the discussion!

**Comment by saurabhdaware** [comment]
> theme.breakpoints.s means nothing to me as a developer without reading Blade docs.

12/10 agree with this. To solve it upto some level, we have added which breakpoint maps to which screen in jsdoc of the breakpoints so in newer versions (version after Box release), this should be simpler.

**Comment by saurabhdaware** [comment]
Closing this issue as
- We have jsdoc comments now that give approximations on which breakpoint refers to which device.
- We can't really name them as `mobile`, `desktop` as more granular breakpoints are often required for responsive UIs
- [Seeing the number of viewports that are used now](https://viewports.fyi/), I don't think so its strongly possible to define certain breakpoint as "mobile" breakpoint. While building UIs, we might have to make UIs responsive for those particular components rather than for devices ([refer to this example](https://github.com/razorpay/blade/issues/1203#issuecomment-1563901366))

Thanks for opening the issue and having this discussion. Happy to reopen and look back at this in future if required.
