### ISSUE TITLE
Bug: Issues in the Card component

### ISSUE THREAD

**Issue by kkyusufk** [razorpay/blade#1140]
**Problem**
While rendering card component, if we do not pass `CardFooterLeading` component and try to render `CardFooterTrailing` only, the buttons are rendered on the left rather than right.
I did not render the CardFooterLeading component, hence the buttons were rendered on the left
![image (3)](https://user-images.githubusercontent.com/22116082/234782653-8d4e27ef-aaee-4579-9a71-6aeacf621ba4.png)

I rendered CardFooterLeading but I did not pass any props, now the buttons do shift to the right
![image (4)](https://user-images.githubusercontent.com/22116082/234782955-ae6923b8-82cb-4d33-af96-7725be117ceb.png)

Note: This behaviour only effects desktop variant.

**Expected Behaviour**
Ideally the buttons in the footer should be placed on the  bottom right.

**Comment by sumitd94** [comment]
Intresting. I think the similar issue will be there on `CardHeader` component as well. because the structure is same over there as well.

Just thinking out loud, I think the `space-between` on the `BaseBox` needs to be rendered dynamically (in the card footer component)

If we have both FooterTrailing and FooterLeading components, then we justify it as `space-between` else we see, If the component is FooterTrailing -- we justify it as may be `flex-end`

```javascript
const footerChildrensArray = React.Children.toArray(children);

  const baseBoxJustifyContent =
    footerChildrensArray.length && footerChildrensArray.length === 2
      ? 'space-between'
      : footerChildrensArray[0]?.props?.actions // FooterTrailing component receives actions as props
      ? 'end'
      : 'space-between';
```
Not the best possible solution, but one of approach in fixing this.

@saurabhdaware @kkyusufk

**Comment by saurabhdaware** [comment]
```ts
  const baseBoxJustifyContent =
    footerChildrensArray.length === 2
      ? 'space-between'
      : 'end'
```

Would this be enough? 🤔

**Comment by sumitd94** [comment]
I thought about this, but in this case if we do not have `footerTrailing` and only `footerLeading` then the content of `footerLeading` will be justified to the end.
I don't think that is the expected behaviour? or is it?

Something like this

<img width="1656" alt="Screenshot 2023-05-03 at 3 16 15 PM" src="https://user-images.githubusercontent.com/29303618/235883881-5f6048b9-81e2-4cab-91a0-6a0bf3d58ab1.png">

**Comment by saurabhdaware** [comment]
aha got it. makes sense.

**Comment by sumitd94** [comment]
Yep, should I raise a PR with this solution?
Will do it both for cardFooter and cardHeader

**Comment by saurabhdaware** [comment]
yeah sure

**Comment by anuraghazra** [comment]
Sounds good to me, @sumitd94 you can raise a patch.

**Comment by saurabhdaware** [comment]
Thanks for creating the issue @kkyusufk 👯
