### ISSUE TITLE
Hover pseudoClass and eventListener support on Blade components

### ISSUE THREAD

**Issue by Kushagra-ag** [razorpay/blade#1163]
It would be good to be able to do something like -
```ts
<Box _hover={{ cssStyles }} onHover={(e) => doSomething()} />
```

This could be beneficial for multiple use cases

- Sending analytics call if user hovers over some element
- Modify styles if user hovers over some element
- On razorpay.com navbar, we need the `onHover` method to show extended navbar items when hovering over menu items like 'Payments' or 'Banking+'

**Comment by saurabhdaware** [comment]
> Sending analytics call if user hovers over some element

This seems like a valid usecase.

I think we'll need it on Button and Link component for sure. Not sure about other components right now. 

> Modify styles if user hovers over some element

This might be something that we won't recommend. Every component has their own set of hover styles which should be consistent.

**Comment by divyanshu013** [comment]
Hover based styles seem like a bad idea on surface, because we handle hover styles for all components internally. Not sure about specifically adding for Box. Could you share some usecases from product?

Regarding `onHover` for analytics events are there actual product usecases for that? I feel hover can accidentally happen and trigger such analytics event as user is moving cursor around 🤔

**Comment by saurabhdaware** [comment]
Agree with Divyanshu about hover part. Can you check with your analytics team once if those events are being used? we took them from older website while migrating so they might be outdated also. Do we get good insights from those hover analytics events?

**Comment by Kushagra-ag** [comment]
@saurabhdaware @divyanshu013 So if you visit razorpay.com and hover over any of the nav menus, you will see some n/w calls with event name `Top Nav Menu Viewed`. 

Apart from analytics, how do you propose we tackle the 3rd bullet point use case in the issue description if we don't have an onHover event listener?

**Comment by saurabhdaware** [comment]
Yup I think for 3rd one we'll definitely have to support `onHover` / `onMouseOver`. 

Marking this as planned // cc @divyanshu013

**Comment by saurabhdaware** [comment]
So did some exploration on this with respect to new navbar. A lot of items that would require `onMouseOver` cannot be replaced by Box as they are semantically "button" element. For example the "Product" in L1 menu or "Top Products" in L2, they are supposed to `styled.button`. Adding `onMouseOver` here wouldn't exactly solve all issues and rather it's discouraged to use Box here in favour of having semantically correct elements.

<img width="691" alt="image" src="https://github.com/razorpay/blade/assets/30949385/cc092b9f-80f1-4eed-bf74-337142120a64">


The part that does require `onMouseOver` on Box is the outer containers to ensure that we don't close them while user is hovering on them.

I tried implementing a POC of this here - [CodeSandbox POC of new Navbar levels](https://codesandbox.io/s/razorpay-new-navbar-ttspcd). I just had to create one reusable custom div component with `onMouseEnter` and `onMouseLeave` callbacks (Let me know if you would want to implement this differently or if I missed some important part).

**Conclusion so far:** Based on the fact that it did not require creating too many custom components for Box (just needed one custom div), and does not have any major consequence on UX, I would suggest to not be blocked on this. 

The discussion to support or not support is still underway but even in future if we support this, you will just have to replace 1 div which should be fine I believe. And if we don't support it, I don't necessarily feel having few `styled.div` instances is bad as long as overall consistency is in place. We definitely don't expect a 100% blade coverage.


### The discussions so far, concerns I have, and why it might not be too obvious to support this

_[These are not collective team's opinions yet. Just my opinions. We're still discussing tradeoffs]_

As you can see in the previous comments, I was in favour of supporting this but after going through usage of `onMouseOver` and possible misuse, I noticed a lot of times it is used as a replacement to what should've been a `button` (easy to miss mistake so not exactly a fault of anyone. But would be great if we can somehow discourage this from blade)

- To perform action on Hover / Clicks is mostly (not always. I agree) the job of action items such as button or link (not to confuse this with Button and Link component from Blade only. But more like semantically they have to be `button` or `a` tag)
- In this case, I would consider Navbar as a bit of an "exception". It's not very common where you would want to build a custom menus. Primarily because we already have SelectInput, and we will have PopOver component which will remove a lot `onMouseOver` usage from consumer's code)


None of these are discussed and debated opinions yet ^^. Might change my opinion. But TLDR is -
- This probably isn't a blocker for Navbar and won't necessarily add too much maintenance (check the codesandbox example I added above)
- We'll parallel discuss and update this github issue 

Do drop a comment if you disagree with any part

**Comment by Kushagra-ag** [comment]
@saurabhdaware so what you are saying is we can't use blade components on most of the places in the navbar?
Since most elements in navbar have some css logic triggering while hovering over them.

Also, none of the button variants provided by blade match the styles in L1 or L2 level menus, so that would require custom implementation as well?

**Comment by saurabhdaware** [comment]
> so what you are saying is we can't use blade components on most of the places in the navbar?
Since most elements in navbar have some css logic triggering while hovering over them.

Yes because those are very one-time custom elements. It's not just about hover, we're in fact leaning towards supporting hover callbacks based on some discussions yesterday but those elements are anyway custom based on look (like you mentioned we don't have a button that renders like them). Having styled components and using blade tokens would make more sense for most of them.

**Comment by saurabhdaware** [comment]
Didn't intent to close this

**Comment by saurabhdaware** [comment]
So we have added `onMouse*` events to Box.

We decided to not add `_hover` right now because in the current frontend-website codebase, it was mostly used on Link or Button or some type of Menu. 

If its a button / link that is supported from blade, then hover styles are handled on our end. If it's a custom chakra component where we render it as button then they become styled-component (added example below)

```jsx
<Box as="a" _hover={{ color: 'primary' }} /> // ->
// ☝🏼  this code turns into this 👇🏼 
styled.a`

:hover {
  // hover styles
}
`
```

Can you share some usecases where something renders as div yet have hover styles? is it a very common pattern in codebase (I couldn't find it in existing frontend-website code)?


The issue with supporting that is, it won't be very useful unless we also support `as="a"`, `as="button"` and hover children styling like -
```jsx
<Box as="a" _hover={{ NavIcon: 'primary', MyTitle: 'primary' }}></Box>
```

In this example, Box renders as `a` and when you hover over Box, it changes heading and icon to blue color.

Right now it can be written as 
```jsx
styled.a`
:hover {
  ${NavIcon}: {
    // hover icon styles
  }
 ${MyTitle}: {
    // hover heading styles
  }
}
`
```

**Comment by saurabhdaware** [comment]
Closing this since mouse handlers are exposed. Pseudo classes we discussed that they can be done with styled-components. Additionally (ignoring the navbar case), we also support clickable cards now which would solve hover and click interactions for cards atleast
