### ISSUE TITLE
Adding isRequired to OTPInput 

### ISSUE THREAD

**Issue by Priyanshu-C** [razorpay/blade#1256]
`OTPInput` component is missing isRequired prop. 

Slack Ref- https://razorpay.slack.com/archives/C01H13RTF8V/p1685690380948209

**Comment by chaitanyadeorukhkar** [comment]
@Priyanshu-C OTPInput will always have `isRequired` as true. So if you inspect the OTPInput component, you'll see `required=true` and `aria-required=true`. This was done because all use-cases of OTPInput will always expect it to be required. 

Do you have any use-case where we might need `isRequired` as `false`? If that's the case, then we can relook at our assumption.

**Comment by chaitanyadeorukhkar** [comment]
Bumping it down to P1 since its not a missing prop but an intentional decision

**Comment by kamleshchandnani** [comment]
if it was intentional then we shall close this issue?

**Comment by chaitanyadeorukhkar** [comment]
I was waiting on @Priyanshu-C to acknowledge this but we can close it. @Priyanshu-C feel free to reopen it if you have any further queries
