### ISSUE TITLE
Box: Support for boxShadow

### ISSUE THREAD

**Issue by kadarsh11** [razorpay/blade#1334]
We need the support of boxShadow prop for Box component

<img width="504" alt="Screenshot 2023-06-21 at 11 28 23 AM" src="https://github.com/razorpay/blade/assets/31586309/3b2fe472-0a8c-457b-9040-442bb4be50b3">

**Comment by chaitanyadeorukhkar** [comment]
Can we not use the card component here?

**Comment by cseas** [comment]
The design we're trying to build is this:

<img width="947" alt="Screenshot 2023-06-29 at 10 45 22 PM" src="https://github.com/razorpay/blade/assets/29686866/2f1e84c1-4814-440b-9807-e5b99fd4ccf7">

I tried replacing our custom styled.div with a Card component but the borders of Blade's card are barely visible. 

<img width="947" alt="Screenshot 2023-06-29 at 10 41 36 PM" src="https://github.com/razorpay/blade/assets/29686866/713d71a3-76bc-4c15-a0b7-0bae41d5c2b8">

We either need boxShadow support on Box to be able to build this or we need border property support on Card component.

[Figma][1]

[1]: https://www.figma.com/file/ytpVeqLD5hQOb1WwrdjBsU/PP%2C-PB---Blade-DS-adoption?type=design&node-id=1296-142854&mode=design&t=vvq3PAWGz4khigKK-4

**Comment by saurabhdaware** [comment]
@saurav12 can you check if this is supposed to be Card or should we let people build this with Box? ^^

**Comment by cseas** [comment]
Ideally, Card should have a border prop so we don't need this workaround. We built the above card using a custom component.

Other sections on the page where we tried to use Blade's Card, its top border is almost invisible.

<img width="1263" alt="Screenshot 2023-07-04 at 12 38 14 PM" src="https://github.com/razorpay/blade/assets/29686866/30db38a5-c6c0-4a41-93c7-729a243a9338">

It looks like Blade's Card component is meant to be used only on a `surface.background.level1` background but the overall background of our page is `surface.background.level2`. We suggested using level1 but our designer said it would make the whole page look dull.

**Comment by saurav12** [comment]
Actually, we discourage the usage of `Cards` on top of the same surface-level colors (which in this case is white-on-white). So there are 2 alternatives here:

- Either go with the level-1 surface and use Card on top of that
- or if that is not feasible in this scenario, go with a higher elevation instead of using `lowRaised`,  i.e. use `midRaised` & `highRaised`.

@cseas Can you share this with the designer and link the Figma file here?

**Comment by cseas** [comment]
> Either go with the level-1 surface and use Card on top of that

We suggested this but our designer said that would make the overall page look dull since level1 is much darker than white.

> go with a higher elevation instead of using lowRaised, i.e. use midRaised & highRaised

The above screenshot I shared is using midRaised elevation only. 🙈 
It's deployed [here][1].

`highRaised` one has the same issue, top border is close to invisible. Here's the [Figma][2].

@saurabhdaware If using Card is not recommended on same surface-level colors, we'll need boxShadow support on Box as per original issue description to build these using Box.

[1]: https://razorpay.com/payment-pages/?EXP_PREVIEW={%22page_migration_payment_pages%22:%22new-infra%22}
[2]: https://www.figma.com/file/ytpVeqLD5hQOb1WwrdjBsU/PP%2C-PB---Blade-DS-adoption?type=design&node-id=1296-142951&mode=dev

**Comment by saurabhdaware** [comment]
We have added `elevation` prop in Box while implementing Skeleton. You can upgrade to this https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%409.1.0
