### ISSUE TITLE
Disabled checkbox with Amount value is having text color as normal.

### ISSUE THREAD

**Issue by Jaynil1611** [razorpay/blade#1373]
While using the checkbox component with the `Amount` component rendered as a value, disabled behavior is not as expected. 
The amount component should have the text color of placeholder when the corresponding checkbox is disabled.
I've attached the below video to help you understand this issue better.

[Figma Link](https://www.figma.com/file/kxLqOeCiJc0Qzh6RmoJnX6/Vendor-Advances-(without-PO)?type=design&node-id=677-281537&mode=design&t=MUuu9VQToc8rDkpV-4)

Here is the code snippet I am trying to run:
```js
<Checkbox value={id} onChange={handleChange} isDisabled={isDisabled}>
  <Amount size="body-medium-bold" value={10000} />
</Checkbox>
```

https://github.com/razorpay/blade/assets/48921037/1f67295f-7c87-4d2c-8396-b3cc54339b39

**Comment by chaitanyadeorukhkar** [comment]
Checkbox component only allows `string` as its children, I'm not sure how the snippet you mentioned is being rendered, ideally, it should be throwing an error 🤔 

But this does seem like a valid use-case where you might need an Amount component within a Checkbox. @anuraghazra can you look into this?

**Comment by anuraghazra** [comment]
This will need design inputs, how will even a disabled amount component look like? @saurav12

**Comment by saurav12** [comment]
Looks like a totally different case to me.
I think this is more similar to a `Table` that contains 5 columns with a `checkbox` as the first item.

| Checkbox | Amount | Date | Number | String |
| -------- | ------ | ---- | ------ | ------|
| [x] | ₹3,000.00 | 12th Feb 23 | 123 | Random text |
| [x] | ₹3,000.00 | 12th Feb 23 | 123 | Random text |
| [x] | ₹3,000.00 | 12th Feb 23 | 123 | Random text |
| ... | ... | ... | ... | ...|

so on...

Or we can expose the `checkbox` without the caption so that it can be utilized in whatever format one would like it to be. We can offer a boolean prop like `withLabel` or something similar which can offer designers a wide category of options to use from.

**Comment by Jaynil1611** [comment]
@chaitanyadeorukhkar @anuraghazra `Checkbox` isn't throwing any error while rendering `Amount` inside it.
[PR](https://github.com/razorpay/x/pull/6934/files#diff-09d3fdeba3b7e056d7ac1de2b6aefe9926576f54f3b9aec38cb8c8c6717261f5) 
[File Link](https://github.com/razorpay/x/blob/850cf0be17d3523882033bb51b0bc89739339c39/src/js/views/VendorPayouts/VendorAdvances/AttachVendorAdvance/AdvanceItemListItem.tsx)  

<img width="660" alt="image" src="https://github.com/razorpay/blade/assets/48921037/0344271d-2c39-44a1-b1d3-4737df9eca8d">

**Comment by Jaynil1611** [comment]
> Looks like a totally different case to me. I think this is more similar to a `Table` that contains 5 columns with a `checkbox` as the first item.
> 
> Checkbox	Amount	Date	Number	String
> [x]	₹3,000.00	12th Feb 23	123	Random text
> [x]	₹3,000.00	12th Feb 23	123	Random text
> [x]	₹3,000.00	12th Feb 23	123	Random text
> ...	...	...	...	...
> so on...
> 
> Or we can expose the `checkbox` without the caption so that it can be utilized in whatever format one would like it to be. We can offer a boolean prop like `withLabel` or something similar which can offer designers a wide category of options to use from.

@saurav12 Only the `Amount` component is tied with `Checkbox` & not the entire row.

**Comment by anuraghazra** [comment]
>  I'm not sure how the snippet you mentioned is being rendered, ideally, it should be throwing an error 🤔

Checkbox accepts React.ReactNode because there were cases where the checkbox label could've contained bold text. 

> I think this is more similar to a Table that contains 5 columns with a checkbox as the first item.

This makes sense, @Jaynil1611 please consult with your designer or put a thread in desgin-system channel to connect with @saurav12 to see if the design can be tweaked because an Amount component cannot have a "disabled" state (thus we cannot make it subtle).

**Comment by chaitanyadeorukhkar** [comment]
@anuraghazra can you follow up on this and get this to closure?

**Comment by snitin315** [comment]
Since there are no follow-up queries, marking this as resolved.
