### ISSUE TITLE
Button: add support for CTA animations

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1385]
We receive regular requests from designers for highlighting a particular CTA with some sort of animation.

Live pages that are using a CTA animation (with Chakra UI):
- https://rzp.curlec.com/payment-gateway/
- https://rzp.curlec.com/payment-links/
- https://rzp.curlec.com/payment-pages/
- https://rzp.curlec.com/payment-buttons/
- https://rzp.curlec.com/invoices/
- https://rzp.curlec.com/pricing/
- https://razorpay.com/pricing/?x-page-infra-variant=new-infra
- https://razorpay.com/payment-links/#overview

New designs requesting a CTA animation:
- [GPT Description Generator][1]

[1]: https://www.figma.com/file/xZP4W0zCEVyjpxn12XtQ96?node-id=877:262343&mode=dev#463480133

**Comment by chaitanyadeorukhkar** [comment]
Checking with design

**Comment by chaitanyadeorukhkar** [comment]
@cseas how are we handling such asks at the moment? Do we have a custom wrapper around Blade's button that animates?

**Comment by cseas** [comment]
We just deny the request and ask the designers to discuss with the Blade team. 😅 
The production links I've given are existing pages not using Blade. Designers usually use these as reference for "Can we do that here too?". 

Received this request in different designs so created the issue to consolidate the use-cases. This isn't a blocker. Currently we're just migrating the pages to Blade without the CTA animation.

**Comment by chaitanyadeorukhkar** [comment]
Makes sense @cseas 

I've discussed it with the team, standardizing CTA animations will be taken up during the rebranding (which is ongoing). Investing efforts in it right now would require major design investments in terms of research. For now, lets do a custom component whenever the ask comes from Design. Since this has been part of our designs for a while now, we shouldn't completely deny such asks either. But we have noted this to be part of the scope during the rebranding changes.

**Comment by saurabhdaware** [comment]
Brand refresh is mostly done. There won't be any animations on new CTA. Can re-open this if such usecase comes again
