### ISSUE TITLE
☂️ Polygon Support

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1394]
There were multiple places where this is coming back as individual prop request so creating this umbrella issue to track everything regarding polygons on landing pages

Previous Context: 
- https://razorpay.slack.com/archives/C01H13RTF8V/p1685421988808309

**Problem Statement:** How to build these polygons on frontend-website?

<img width="500" alt="image" src="https://github.com/razorpay/blade/assets/30949385/642b48fe-1cdf-48d9-8c83-b8cc083266b3"> <img width="200" alt="image" src="https://github.com/razorpay/blade/assets/30949385/5616b0b9-62ab-4681-9487-8d9c46a41746">

**Existing Solution:** Build these as custom styled-components in frontend-website repo since it's limited to razorpay.com

**Consumer Concerns:** [Building these as custom components is an overhead](https://docs.google.com/spreadsheets/d/1RnjvDwNOAMnrLN2-2KIyEBwwX0cAmKK2JTtI3gNK2rA/edit#gid=0&range=12:12). developer experience will be better if 
- Box supports all props that are required for building polygons
- We standardise polygons on blade and maybe create a Polygon component

**Props we will have to support on Box for Polygons:**

- role
- backgroundImage
- transform
- transformOrigin
- boxShadow
- clipPath

**Comment by saurabhdaware** [comment]
## Opinions

### Regarding supporting all polygon props on Box

Props we will have to support for Polygons

- role
- backgroundImage
- transform
- transformOrigin
- boxShadow
- clipPath

I don't see much harm in just supporting all props that polygon requires. My concerns are more on the overall call side-
- Should we start treating Box as primitive component for building other custom components? Because right now the usecase at hand is creating polygons. In future we'll have lots of other custom components with props specific to the project.

### Regarding creating custom Polygon component

I am not much in favour of creating Polygon component from blade because we haven't seen these polygons much outside of razorpay.com. Will also prefer to wait for design revamp and see what type of designs we eventually build to avoid duplicate efforts.

**Comment by cseas** [comment]
> For frontend-website teams: Create a reusable Polygon styled-component in frontend-website common components to get unblocked

This is done (partially). For Payment Pages, we had to take up adhoc of coming up with a custom primitive to implement this in a clean way since Blade's Box had too many restrictions for this use-case. Code for reference available [here][1].

To elaborate on the full requirement, this wasn't a one-off implementation even for a single page. We needed a reusable component that:
- can accept different background colors/gradients
- can accept different clip paths
- supports responsive props since the polygons change shape on mobile/desktop
- supports spacing props to adjust the layout for different sizes of content
- has correct type definitions for all props

Creating the above requirement with a styled div was getting messier and hard to read/understand with every iteration so creating the custom Box primitive introduced unplanned overhead. As a general opinion internally, use of a custom primitive isn't something most devs are in favour of. Looking for suggestions from Blade team on what could we improve here for smoother handling of these use-cases since polygons are very prominent in website designs. 

The rebranding might ease the polygon shapes/angles maybe but website will always have need for colorful backgrounds. Box doesn't support Blade's own full range of color tokens for backgrounds either so polygons or any sort of backgrounds in general are unpredictable in general for devs. 

For example, we needed a long running [discussion][2] to change the purple gradients to blue ones that used Blade's color tokens. If not a component, hoping for some design guidelines from Blade on how designers use gradients and backgrounds in designs.

Another example of confusions arising from missing background guidelines can be seen on production here:
https://razorpay.com/payment-pages/
We use Card component at a lot of places on this page but it's borders are barely visible since the page background our designs had (surface level2) aren't compatible with Blade's Card. Our designer also pointed out that the card's borders seemed much more visible on Figma than they came out in actual implementation so maybe there's some inconsistency there.

[1]: https://github.com/razorpay/frontend-website/blob/master/src/pages/BladePaymentPages/components/CustomBoxWithBackground.tsx
[2]: https://razorpay.slack.com/archives/C01H13RTF8V/p1686049441148039?thread_ts=1685421988.808309&cid=C01H13RTF8V

**Comment by saurabhdaware** [comment]
Makes sense. We were also discussing what to do about gradients. Will update once we have some conclusion.

**Comment by cseas** [comment]
Just got a [new request][1] to use gradients different from Blade tokens.
The page overall has a different color scheme than Blade. More purple instead of blue. Payment Pages designs were originally purple as well. Feels like we're going in circles without a conclusion here. 😕 

<img width="954" alt="Screenshot 2023-07-13 at 5 35 50 PM" src="https://github.com/razorpay/blade/assets/29686866/7f47cb21-c06a-489a-a9e4-4282607b7b83">

[1]: https://razorpay.slack.com/archives/C03SBALMYJV/p1689249813411759?thread_ts=1688972720.741319&cid=C03SBALMYJV

**Comment by saurabhdaware** [comment]
Yup the exact problem we were discussing internally. We're on the same page. Will let you know once we have something. Meanwhile for this current design, can you ask the designer to reach out to blade designers and see what can be done?

**Comment by saurabhdaware** [comment]
MoM from our internal discussion
- It's hard to standardise background colors / gradients right now because brand refresh is expected to happen soon which might change how we standardise some of these things and we would want to avoid duplicate efforts or early breaking changes. For current designs, you can ask designers to reach out to our design team and we can evaluate and take decision for particular scenarios. 
- We have already exposed brand colors on `backgroundColor` and also exposed `backgroundImage` attribute recently on Box component.
- In addition to that, we will expose these props to help build Polygons 
  - transform
  - transformOrigin
  - clipPath
- We will not be exposing boxShadow since we have `elevation` prop for shadows. The elevation prop although only supports shadows of containers and might not cover all polygon scenarios. So any polygon that might require boxShadow will have to be built as custom component.
- In frontend-website, `role` attribute was used to set "presentation" role which is fine if its not set since divs don't have any special accessibility behaviour so we won't support `role`

**Comment by cseas** [comment]
Will Box accept arbitrary colors or do we still need a custom Box primitive to build the above purple polygons? 😕

**Comment by saurabhdaware** [comment]
Turning this into a P0 because another usecases came up and effort won't be that high https://razorpay.slack.com/archives/CMQ3RBHEU/p1695883075772109

**Comment by saurabhdaware** [comment]
> Will Box accept arbitrary colors or do we still need a custom Box primitive to build the above purple polygons? 😕

As of now we won't. We expect purple polygons to go away after brand refresh. Can take a call after brand refresh if the colors don't get standardised.

**Comment by saurabhdaware** [comment]
Can be solved along with #1679
