### ISSUE TITLE
In controlled Autocomplete, selected item is getting updated without explicit setState call 

### ISSUE THREAD

**Issue by sujoys12** [razorpay/blade#1676]
In the controlled component, the value should be updated only if the consumer explicitly updates it, i.e. makes a setCurrentSelection call inside the onChange callback.
But in this case, it's getting updated without the setState call.

Code sandbox - https://codesandbox.io/s/elated-vaughan-csqj3f

**Comment by snitin315** [comment]
@sujoys12 I believe this is expected behavior because we are explicitly passing `value={currentSelection}` to the Autocomplete. So it will be selected whenever we update the value via `setCurrentSelection` regardless of where this is being called.

**Comment by saurabhdaware** [comment]
> So it will be selected whenever we update the value via setCurrentSelection regardless of where this is being called

@snitin315 I think in this case the issue is that it is updating even when you don't call `setCurrentSelection` (when you go and change dropdown from UI without calling `setCurrentSelection` in onChange)

I am able to reproduce it by going to the demo mentioned in the issue, and clicking on the input, selecting item. It selects the item but it shouldn't because we're not calling setCurrentSelection in its onChange

**Comment by snitin315** [comment]
@saurabhdaware Gotcha! Raised a fix.
