### ISSUE TITLE
Android and iOS builds keeps crashing on release builds on Blade upgrade to v10

### ISSUE THREAD

**Issue by import-yuv** [razorpay/blade#1677]
When upgrading the blade from 9.7.0 to 10 in PG mobile app,  getting the following error. From the error log it seems to be coming from Reanimated v3.

Error: 
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: [Reanimated] Using dev bundle in a release app build is not supported. Visit https://github.com/software-mansion/react-native-reanimated/issues/4737 to find more information on how to fix this issue., js engine: hermes
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw

```

Slack thread- https://razorpay.slack.com/archives/C01H13RTF8V/p1695714431312989

**Comment by mohit23x** [comment]
ℹ️ https://github.com/software-mansion/react-native-reanimated/pull/4732
ℹ️ https://github.com/software-mansion/react-native-reanimated/issues/4737

**Comment by chaitanyadeorukhkar** [comment]
Reposting the findings & solution here. @mohit23x @import-yuv let me know if this works.

So Reanimated Plugin behaves differently on production & differently on development

- To create a development bundle you use `NODE_ENV=development` & `BABEL_ENV=development`. These two env variables tell the babel plugin that it needs to create a development bundle. 
- To create a production bundle you use `NODE_ENV=production` & `BABEL_ENV=production`. These two env variables tell the babel plugin that it needs to create a production bundle. 
- Now when you are running on your local, with JS Dev mode checked off (which means you want a development bundle), you need to set `NODE_ENV=development` & `BABEL_ENV=development`
- Now when you are running on your local, with JS Dev mode checked on (which means you want a production bundle), you need to set `NODE_ENV=production` & `BABEL_ENV=production`
- Reanimated added strict checks for v3
- We were shipping blade with reanimated plugin in development mode which worked fine before the v3 upgrade in both development & production
- After v3 upgrade, blade enforcing reanimated plugin in development broke your app. Which meant we had to first remove shipping with the reanimated plugin.
- Now I’ve removed reanimated plugin (#1691) with our builds but reanimated will still do strict checks on PG Mobile app since you also use the reanimated plugin. 
- So you need to do 2 things - 1. Use Blade that ships without reanimated plugin. (this one) 2. Use `NODE_ENV=development` & `BABEL_ENV=development` for all your development needs and `NODE_ENV=production` & `BABEL_ENV=production` for all your production needs. 
- This means you can no longer check on and off JS Dev mode and expect things to work fine, you need to set your env vars to development when JS Dev mode is on and set it to production when JS Dev mode is off
- When you are making production builds & releases you also need to make sure you are setting `NODE_ENV=production` & `BABEL_ENV=production`


I’ve confirmed this by creating a barebones project which has reanimated & Blade. Can you incorporate all this on mobile app too?
