### ISSUE TITLE
Modal should not retain focus on previously focused element

### ISSUE THREAD

**Issue by parichay28** [razorpay/blade#1688]
Repro: Focus via keyboard on close button & dismiss modal via keyboard. Modal retains focus on reopening.

Expected Behaviour: Post [this](https://razorpay.slack.com/archives/CMQ3RBHEU/p1695989584102239?thread_ts=1687940576.919669&cid=CMQ3RBHEU), focus states should be reset on modal dismiss

<video src="https://github.com/razorpay/blade/assets/43565572/2b47bb89-c6be-4c8d-9993-3650a5139c34" controls="controls" style="max-width: 730px;">
</video>

**Comment by bhaveek424** [comment]
Hi @parichay28, It's not retaining focus on previous elements for example try focusing on any of the checkboxes or the buttons, exit the modal and open again, you'll find the focus on the close button. The focus is on close button for accessibility.

**Comment by anuraghazra** [comment]
@parichay28 can you provide reproduction steps for this, like what inputs did you pressed? 


> Repro: Focus via keyboard on close button & dismiss modal via keyboard. Modal retains focus on reopening.

I believe this is to be expected, focus-visible's heuristics is that if you use keyboard it will show focus, but if you use mouse it wont.

**Comment by parichay28** [comment]
Uploading screen_recording.mov…

> focus-visible's heuristics is that if you use keyboard it will show focus
Ack. When a modal is dismissed & re-opened, shouldn't the focus state be lost as well since re-opening modal is a fresh instance from user's POV & should not retain previous focus states?

**Comment by anuraghazra** [comment]
> when a modal is dismissed & re-opened, shouldn't the focus state be lost as well since re-opening modal is a fresh instance from user's POV

Focus state does get lost, just that you are focusing on close button before closing the modal and close button also happens to be the "[initialFocus](https://github.com/razorpay/blade/blob/6cb608e916d2a28261fa8f1a279638c757650599/packages/blade/src/components/Modal/Modal.web.tsx#L142)" when modal opens, so it's giving you the impression that focus is retained even after component is unmounted. 

But this is the expected behaviour. You can also change the initial focus by passing the `initialFocusRef` prop. [csb demo](https://codesandbox.io/s/jvrm9s?file=/App.tsx&utm_medium=sandpack)

**Comment by anuraghazra** [comment]
@parichay28 Closing this as it's expected behaviour, feel free to raise a thread on slack if you have further queries.
