### ISSUE TITLE
Multi-select dropdown component breaks with certain props

### ISSUE THREAD

**Issue by anilprzp** [razorpay/blade#1721]
### Environment
Blade version - `10.15.0`
Browser - Chrome v112.0.5615.137

### Description
Passing a certain set of props to multi-select dropdown is breaking the component. For reproducing the bug - 
1. Go to the multi-select example on storybook - https://master--61c19ee8d3d282003ac1d81c.chromatic.com/?path=/story/components-dropdown-with-select--with-multi-select
2. Paste the following snippet with specific set of props - 
    ```App.tsx
    import { 
      Dropdown, 
      DropdownOverlay,
      SelectInput,
      ActionList,
      ActionListItem,
    } from '@razorpay/blade/components';
    
    function App(): React.ReactElement {
      return (
        <Dropdown 
          selectionType="multiple"
        >
          <SelectInput
            label="City"
            placeholder="Select your City"
            name="action"
            value={["mysore"]} // value prop is added extra
            onChange={({ name, values }) => {
              console.log({ name, values });
            }}
          />
          <DropdownOverlay>
            <ActionList>
              <ActionListItem title="Mumbai" value="mumbai" isDisabled /* isDisabled is added extra */ />
              <ActionListItem title="Pune" value="pune" />
              <ActionListItem title="Bangalore" value="bangalore" />
              <ActionListItem title="Mysore" value="mysore" />
            </ActionList>
          </DropdownOverlay>
        </Dropdown>
      )
    }
    
    export default App;
    ```

Please find the screen recordings of how to reproduce the bug - 

https://github.com/razorpay/blade/assets/95009160/8e91ab1b-fec5-487f-ba4c-0f964c0a9aba

https://github.com/razorpay/blade/assets/95009160/801f5928-9f97-4563-ac01-e0b03b57c62f

**Comment by anilprzp** [comment]
**Please note that this is a potential release blocker for XPayroll team**

**Comment by anuraghazra** [comment]
@anilprzp we will prioritize this ASAP.

**Comment by saurabhdaware** [comment]
@anilprzp can you also share the code for your X Payroll component?

The error in sandpack seem due to the react refresh in dev-server. It works when the page is refreshed properly - https://codesandbox.io/s/snowy-water-687dxg

The error on X Payroll might be due to some other race condition. I can take a look

**Comment by anilprzp** [comment]
@saurabhdaware here are the references - 
https://github.com/razorpay/opfin/blob/master/ui/src/components/Knit/KnitHrms/Settings/EmployeeContractorMapping.tsx#L190-L200

https://github.com/razorpay/opfin/blob/master/ui/src/components/Knit/KnitHrms/Settings/components/EmployeeTypesMappingCard.tsx#L117-L136

Let me know if connect over a call is needed. I was able to reproduce the issue with final build as well.

**Comment by snitin315** [comment]
@anilprzp Can you try this version of Blade and check if it fixes the issue for you?

```
yarn add https://pkg.csb.dev/razorpay/blade/commit/2b5485fe/@razorpay/blade
```

**Comment by saurabhdaware** [comment]
@anilprzp Are you trying to disable items in both the dropdowns when they are selected? 

We cannot exactly disable the item that is selected item for that particular dropdown. So if you select an item, then you can't disable it until you remove that item from selection.

If what you're doing is disable item from one dropdown, when its selected in other, you might have to make sure same state is not changing for both dropdowns.


Can you check if some implementation like this will work for you? here I am not disabling items in one dropdown and I am not allowing other dropdown to change the disabledItems state.
https://codesandbox.io/s/snowy-water-687dxg?file=/App.tsx

Let me know if I misunderstood your usecase since I lack some context in your code.
