### ISSUE TITLE
Pagination controls issue for async paginated data

### ISSUE THREAD

**Issue by sujoys12** [razorpay/blade#1961]
In storybook, a static list has been used. There the whole list is passed as data props in the table. So pagination component can derive the state of prev and next buttons based on the page size.

Now when we use BE paginated api to populate the list data, the prev and next buttons remain disabled, as FE only fetches required items from api as per the page size. Ideally, there should be an option to send the total count in the pagination component for pagination control btns.

**Comment by chaitanyadeorukhkar** [comment]
You should fetch more data whenever you've reached the last page. Last page is when your current page multiplied by the page size is greater than or equal to your total fetched data.

```tsx
 const pageSize = 10; // default page size for the table

 const handlePageChange = ({ page }) => {
    if (page * pageSize >= data.nodes.length) {
      fetchMoreData({page})
    }
  };

return (
  <Table 
      data={data}
      pagination={<TablePagination defaultPageSize={10}  onPageChange={handlePageChange} />}
  />
    ...
  </Table>
);
```

Although, I agree this is a temporary solution and has the following issues:
1. The next button will be disabled for an instance.
2. The total page count will keep increasing as you move forward
3. The page number picker on pagination will keep changing as you fetch more data

I can solve 1 & 2 by accepting a `totalItemCount` which your API should return so that we know how much data we have on the backend. We can compute everything about pagination accordingly. I'll discuss this with the team once and we can ship this soon.

Solving 3 is a challenge since when you jump to a specific page, you might have to fetch all the data up till that page. The current variation of number picker works better with static data. We might have to rethink this a bit... I will check on this and let you know.

**Comment by sujoys12** [comment]
> when you jump to a specific page, you might have to fetch all the data up till that page.
Do you suspect any issue if we fetch only the required items for the table using the skip and count param of paginated BE apis?

**Comment by AnkitaBagale** [comment]
@chaitanyadeorukhkar 
Do we have to keep all the data in local state to use pagination?
Can we not fetch only the data required for any particular page and pass only that to Table component?

And in addition we can pass totalCount. so that 1. disabled state for next button, 2. page numbers selector:  can be derived from currentPage, pageSize and totalCount
