### ISSUE TITLE
Dropdown values are not truncated

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2275]
<img width="266" alt="image" src="https://github.com/razorpay/blade/assets/69760792/2c8bb879-7172-4751-b35d-e3e5ec8ed68f">

```
  <Dropdown selectionType={selectionType} onOpenChange={handleOnOpenChange}>
      <AutoComplete
        label={label}
        name={name}
        value={values}
        inputValue={searchValue}
        placeholder={placeholder}
        onChange={onChange}
        onInputValueChange={handleInputValueChange}
        filteredValues={filteredValues}
        labelPosition={props.labelPosition}
        isRequired={props.isRequired}
        necessityIndicator={props.isRequired ? 'required' : undefined}
      />
      <DropdownOverlay>
          <ActionList>
            {options.map((option) => {
              return (
                <ActionListItem
                  key={option.value}
                  title={option.title}
                  value={option.value}
                  description={option.description}
                />
              );
            })}
          </ActionList>
        )}
      </DropdownOverlay>
    </Dropdown>
```

**Comment by saurabhdaware** [comment]
In `10.23.1` we added support for changing the width of overlay when selectinput is used. So you can now pass `minWidth`, `maxWidth`, `width` to DropdownOverlay and adjust the width for your content.

Truncation we thought wouldn't be the right thing here because email ids should always be visible completely, and breaking text into another line will make item height inconsistent.

We'll still see if we can do something here but otherwise you can get unblocked by changing the DropdownOverlay width now

**Comment by saurabhdaware** [comment]
Let me know if this gets you unblocked. If not I'll add this back as P0 and see what else we can do

**Comment by AnkitaBagale** [comment]
hey @saurabhdaware tried it, still not working.
