### ISSUE TITLE
Bug: fix occurrences of a11y roles that don't exist on native

### ISSUE THREAD

**Issue by divyanshu013** [razorpay/blade#668]
We've some occurrences where we're using the same roles on web and native but not all web roles exist on native such as `group`. To replicate run `yarn test:react-native`

<img width="1617" alt="image" src="https://user-images.githubusercontent.com/6682655/186612686-216b6a83-3436-4e0a-a124-fa6ab023363e.png">

**Comment by jainpawan21** [comment]
Hi @divyanshu013, Is this issue available to pick?

**Comment by snitin315** [comment]
Fixed in master, I can see only two such logs from the makeAccessible test, which is intentional & expected.

https://github.com/razorpay/blade/blob/8d2105a86eb02ab0b79dd652d565af83c50da9b5/packages/blade/src/utils/makeAccessible/__tests__/makeAccessible.native.test.ts#L39-L44

https://github.com/razorpay/blade/blob/8d2105a86eb02ab0b79dd652d565af83c50da9b5/packages/blade/src/utils/makeAccessible/__tests__/makeAccessible.native.test.ts#L56

<img width="988" alt="Screenshot 2023-10-12 at 10 53 15 AM" src="https://github.com/razorpay/blade/assets/46647141/ff399b52-47c2-494e-a095-6cac1cc36f9c">
