### ISSUE TITLE
Support for `keyboardType = 'numeric'` on `BaseInput` & `OTPInput`

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#736]
The `BaseInput` [decision doc mentions `numeric`](https://github.com/razorpay/blade/blame/master/packages/blade/src/components/Input/BaseInput/_decisions/_decisions.md#L49) as a valid value for `keyboardType` but the `BaseInput` [implementation doesn't support `numeric`](https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Input/BaseInput/BaseInput.tsx#L124) as a valid value. Is this intentional? Can we add support for `numeric`? Due to this constraint, we've added default `keyboardType` as `decimal` instead of `numeric` for `OTPInput`. After adding support for `numeric`, we should also change the default for `OTPInput` as `numeric`

**Comment by chaitanyadeorukhkar** [comment]
@kamleshchandnani can you clarify this?

**Comment by divyanshu013** [comment]
Could be a miss 🤔

**Comment by divyanshu013** [comment]
@kamleshchandnani could you check the OP please?

**Comment by kamleshchandnani** [comment]
so not having `numeric` type was intentional because of the keyboard that is shown on iOS. [Reference](https://css-tricks.com/better-form-inputs-for-better-mobile-user-experiences/). I'll update the API decisions.


<img width="1066" alt="Screenshot 2022-10-21 at 10 26 19 AM" src="https://user-images.githubusercontent.com/11384858/197115384-f172b432-1200-4767-80a7-b9d1c270dd30.png">



If this is causing confusion then essentially what we can do is for consumer components we can accept `keyboardType=numeric` instead of `decimal` and internally pass `decimal` to `BaseInput` component. Let me know what do you folks think?
