### ISSUE TITLE
Create `Divider` component 

### ISSUE THREAD

**Issue by kamleshchandnani** [razorpay/blade#978]
We have implemented `Divider` in two places now:
* Cards
* ActionList

This seems to increase the need for `Divider` as a generic component. So we shall create this as a component sooner rather than later

**Comment by abhieshekumar** [comment]
folks will want to pick it up. As an exercise -
- tried out a [dummy divider component](https://codesandbox.io/s/divider-example-forked-coydmt?file=/src/Divider.tsx) (I know there is a whole process that happens before 🙈).
- uses Transient props, which prevents props from getting added to final HTML #714

Please let me know how to proceed? @kamleshchandnani @divyanshu013

**Comment by divyanshu013** [comment]
For this component, you can go through the existing components (some are listed in the OP) and first list down the usecases and a proposed API here.

Once we've the possible usecases and an API we can proceed to the implementation (this will help minimizing code changes later).

**Comment by abhieshekumar** [comment]
got it. thank @divyanshu013 not quiet sure what you mean by `listed in the OP`, can you please share?

**Comment by divyanshu013** [comment]
I meant the ones listed in the parent comment [here](https://github.com/razorpay/blade/issues/978#issue-1556205532)

**Comment by abhieshekumar** [comment]
Please check [this document](https://docs.google.com/document/d/1ZQbea8v8gGpwSYQAnpTcL3SCgyWYYzNX9AFwoZyv2PI/edit?usp=sharing)

**Comment by divyanshu013** [comment]
Thanks for the doc. The design research is currently pending on this from our design team (current draft is [here](https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade---Payment-Light?type=design&node-id=37369-560819&t=4gjztutJU1ndRBvb-0)).

Since this is pending a thorough design research we would like to currently scope the usecases only to what we've in the code i.e. the components like bottom sheet, cards, action list, etc. Things such as orientation, type, alignment etc should be skipped for now.

As next steps you can scope out the doc and propose an API that works only for our existing components (so you'll have to get rid of things which don't have a usecase in existing components - keeping things simpler).

After that perhaps draft out a PR that refactors one component to use this simple `Divider` component. We can review that and if it looks good you can refactor other components too.

**Comment by abhieshekumar** [comment]
Hi @divyanshu013 , looked through the usage of `Divider` component within our codebase. Listing them down [in this document](https://docs.google.com/document/d/1kVIDa2MEU-xG4s9UBUVtGf1mrek2Xu30kDu4Ko93hL0/edit#). Please check.

**Comment by divyanshu013** [comment]
Seems good overall. One comment on the doc: this should be a `div` / `View` because `hr` should be used to separate mostly paragraph level elements.

**Comment by abhieshekumar** [comment]
@divyanshu013 please check this https://github.com/razorpay/blade/pull/1258

**Comment by divyanshu013** [comment]
Approach seems good, need to do for all other components which are using divider

**Comment by abhieshekumar** [comment]
@divyanshu013 
- refactored other components. [Please check](https://github.com/razorpay/blade/pull/1258/files) 
- wanted to confirm, do we also need to add test cases and stories for this current divider?

**Comment by anuraghazra** [comment]
Done in #1258
