### ISSUE TITLE
Dropdown: Add more story/recipes for covering various use cases of dropdown

### ISSUE THREAD

**Issue by kamleshchandnani** [razorpay/blade#990]
1. using Dropdown for building navigation menu(navbars)
2. using Dropdown for showing a context menu kind of UX used when clicking on user avatar

Enhancement for #988

**Comment by saurabhdaware** [comment]
More stories and recipes were added here - https://github.com/razorpay/blade/pull/1161

> using Dropdown for building navigation menu(navbars)
> using Dropdown for showing a context menu kind of UX used when clicking on user avatar

These 2 we don't support from implementation perspective itself. Can probably add stories for this when we implement it. 

I think we can close this issue since we have satisfactory amount of stories for Dropdown and ActionList now.
